framework:
  - terraform
directory:
  - terraform
output:
  - cli
  - sarif
output-file-path:
  - console
  - checkov-results.sarif
compact: true
quiet: false
skip-check:
  - CKV_AZURE_119
  - CKV_AZURE_50
